project_id = "burrycqviohhzzjxogeh"

[functions.telegram-auth]
verify_jwt = false

[functions.telegram-bot]
verify_jwt = false

[functions.user-action]
verify_jwt = false

[functions.admin-action]
verify_jwt = false

[functions.monthly-reset]
verify_jwt = false
